name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build buildenv -t danios1-buildenv
           docker run --rm -it -v "$(pwd)":/root/env danios1-buildenv
           make build-x86_64
